### ISSUE TITLE
Bus stop data URL has changed

### ISSUE THREAD

**Issue by rarkins** [kaihendry/ltabus#1]
FYI, this URL referenced in the README now returns a 404: http://www.mytransport.sg/content/dam/mytransport/DataMall_StaticData/Geospatial/BusStops.zip

It's possible that this data has now moved into the "dynamic"/API section and requires an API key.

From: http://www.mytransport.sg/content/dam/mytransport/DataMall_StaticData/LTA_DataMall_API_User_Guide.pdf

> Dataset URL http://datamall.mytransport.sg/ltaodataservice.svc/BusStopCodeSet
> Description Lists details for all bus stops in Singapore (code, road, description).

When I query that though, I get a result with only 50 stops. Not sure if their API is broken or I am sandboxed.

**Comment by kaihendry** [comment]
Thanks for noticing. You in Singapore?! You use my app? ;)

**Comment by cheeaun** [comment]
:+1:

**Comment by rarkins** [comment]
Actually I found this repo by accident after having troubles with the mytransport API and Googling for example code. Got suckered into clicking the bus stops link!

**Comment by kaihendry** [comment]
Yes, I've now noticed http://datamall2.mytransport.sg/ltaodataservice/BusStops only returns a subset of the bus stops. WEIRD.

```
jq .value[].BusStopCode BusStops | wc -l
500
```

I am going to close this, since it's a dataMall issue, not mine. #smartNation
