### ISSUE TITLE
Node JS module : Feature Request!

### ISSUE THREAD

**Issue by Rian9771** [kaihendry/ltabus#2]
Hi @kaihendry ,

Thank you for this. I have been using LTA bus for a while. Works really well. I am working on a project, using google maps/transit API to query BUS arrival times. But the way LTA bus works is much much better. I like the way it shows all bus in that particular stop. 

I was wondering if i could request another feature/variation of this. Would you be interested in creating a node.js module for this so it can be easily imported in one of these projects?

https://github.com/MichMich/MagicMirror
https://github.com/MichMich/MagicMirror/tree/develop/modules

Cheers!

**Comment by kaihendry** [comment]
Hey @Rian9771 ... how did you find it? I thought only myself and my wife uses it. ;)

Can't you embed https://bus.dabase.com/ via an iframe? It isn't a JS driven application.

**Comment by Rian9771** [comment]
@kaihendry , i guess it's popular. :)

I do not come from a programming background. Hence i struggle when it comes to creating something from scratch. :). I looked into embedding using iframe, i do not believe that would work here. I just need to print the values displayed on the page for a certain bus stop. So, a script that prints out the time when the bus stop number is passed (if that makes any sense). 

Is there any other way to do this? Other than iframe?

Cheers!
